Fix issue #35 and Travis
baumer-lab/fec16 pull request #37
Opened 2020-11-01 21:48 UTC by mariumtapal

I've mainly fixed this issue. In both `results_senate` and `results_house`, in the `party` variable, there are very few entries with `R ` and `D `. Notice the space after. I tried fixing this as well (in addition to the `R` and `D` without the spaces), but for some reason, it does not change. I can try hard coding the values with indexing but I don't think that is a good idea for reproducibility reasons

2020-11-02 00:20 UTC, beanumber requested changes

2020-11-02 00:20 UTC, beanumber commented on DESCRIPTION
> +Version: 0.1.3
Can you change this to 0.1.2.9001? We'll go to 0.1.3 once we're ready to resubmit to CRAN.

2020-11-02 00:20 UTC, beanumber commented on data-raw/process_results.R
> +    party = if_else((party == "R")|(party == "R "), "REP", party),
Can you trim using `str_trim()` and see if you can catch all cases?

2020-11-05 23:46 UTC, mariumtapal commented
@beanumber fixed! thank you for reminding me of `stringr`!

2020-11-06 14:23 UTC, beanumber approved these changes

2020-11-06 14:23 UTC, merged