Fix to save dm visual!
baumer-lab/fec16 pull request #41
Opened 2020-11-12 02:46 UTC by mariumtapal

@beanumber I've created a possible fix. The image quality isn't as crisp as with manually saving but the fix works.

Before calling `webshot::webshot()` I had to create an HTML file. `htmlwidgets::saveWidget()` doesn't let you save to a particular sub-directory therefore `fec16-dm.html` is in the main directory. I added it to `.RBuildignore` for CRAN size reasons.

2020-11-12 15:17 UTC, beanumber requested changes

2020-11-12 15:17 UTC, beanumber commented on .Rbuildignore
> +^fec16-dm.html
Let's not have this in the repo

2020-11-12 15:18 UTC, beanumber commented
This looks great. Can you just remove the HTML stuff from the commit? We don't need that in the repo. We just need the resulting JPEG.

2020-11-13 00:48 UTC, mariumtapal commented
@beanumber Added see also section to readme for related packages and removed the HTML file

2020-11-13 14:17 UTC, beanumber approved these changes

2020-11-13 14:17 UTC, merged